# Generated by Django 4.2.14 on 2024-07-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='men',
            old_name='pt',
            new_name='Product_Type',
        ),
        migrations.RenameField(
            model_name='men',
            old_name='st',
            new_name='Style_Type',
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('size', models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', 'XXL')], max_length=20)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Women_by_product_type', to='products.product')),
                ('style_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Women_by_style_type', to='products.product')),
            ],
        ),
    ]
